# Generated by Django 5.2.1 on 2025-09-08 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications', '0002_rename_content_notification_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='选择用户组接收此通知', related_name='received_notifications', to='auth.group'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', '公告'), ('internal', '内部通知')], default='announcement', help_text='选择通知类型', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(blank=True, help_text='选择多个用户接收此通知', related_name='received_notifications_multi', to=settings.AUTH_USER_MODEL),
        ),
    ]
